### ISSUE TITLE
name from fasta header instead of fasta file name

### ISSUE THREAD

**Issue by martin-raden** [Alexander-Mitrofanov/CRISPRspacerEvolution#10]
use fasta header sequence name for "Name" output in summaries

**Comment by martin-raden** [comment]
otherwise the forwarding of the input to spacer placer will result in "accession number = input" for all entries...
![grafik](https://github.com/user-attachments/assets/e03f292e-f077-4618-be07-15641c6d3981)

**Comment by Alexander-Mitrofanov** [comment]
fixed now
