### ISSUE TITLE
[evo] no X11 available on server ...

### ISSUE THREAD

**Issue by martin-raden** [Alexander-Mitrofanov/CRISPRspacerEvolution#12]
given [second point of this list](https://github.com/fbaumdicker/SpacerPlacer?tab=readme-ov-file#known-issues-solutions-and-tips) and the error message on the server:

```sh
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-galaxy'
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display
```

we need to call spacer placer with `--no_plot_reconstruction`

do you need the plots?

**Comment by Alexander-Mitrofanov** [comment]
can we do something like:

sudo apt-get install xvfb
xvfb-run -a python your_script.py

**Comment by martin-raden** [comment]
https://rna.informatik.uni-freiburg.de/review/CRISPRse/Result.jsp?toolName=CRISPRse&jobID=0321533
