### ISSUE TITLE
logo needed for webserver

### ISSUE THREAD

**Issue by martin-raden** [Alexander-Mitrofanov/CRISPRspacerEvolution#6]
we need a graphic/logo for the tool to be shown on the start page

http://rna.informatik.uni-freiburg.de/

**Comment by Alexander-Mitrofanov** [comment]
![placerholder_logo](https://github.com/user-attachments/assets/d2072a57-db38-482c-8ef3-84859cf54ba5)

can we use that one as a placeholder?
